services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zofy_backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: zofy_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

